import { Case, Dealer, Customer, RiskScore, RiskSignal, EvidenceItem, VerificationTask } from '@/types';

/**
 * SYNTHETIC MOCK DATASET
 * Used in Phase 1 for frontend verification workflows and scenario preview.
 * Corresponds with backend seed scenarios.
 */

export const MOCK_DEALERS: Dealer[] = [
  {
    id: 'DLR-APX-01',
    dealer_code: 'DLR-APX-01',
    name: 'Apex Solar Equipment Pvt Ltd',
    business_name: 'Apex Solar Solutions',
    gstin: '27AAACA1234A1Z5',
    pan: 'AAACA1234A',
    cin: 'U40106MH2018PTC309812',
    address: 'Plot 45, MIDC Phase II, Bhosari',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411019',
    contact_email: 'compliance@apexsolar.synthetic',
    contact_phone: '+91-9823000001',
    status: 'active',
    risk_tier: 'low',
    total_cases: 14,
    flagged_cases: 0,
    created_at: '2026-01-05T09:00:00Z',
  },
  {
    id: 'DLR-SUN-02',
    dealer_code: 'DLR-SUN-02',
    name: 'SunPower Retail & Infra Solutions',
    business_name: 'SunPower Infra',
    gstin: '24BBBCB5678B1Z2',
    pan: 'BBBCB5678B',
    cin: 'U40300GJ2020PTC412098',
    address: '12, Commercial Hub, Ring Road',
    city: 'Surat',
    state: 'Gujarat',
    pincode: '395002',
    contact_email: 'accounts@sunpowerinfra.synthetic',
    contact_phone: '+91-9823000002',
    status: 'under_review',
    risk_tier: 'medium',
    total_cases: 9,
    flagged_cases: 3,
    created_at: '2026-01-10T11:30:00Z',
  },
  {
    id: 'DLR-RAD-03',
    dealer_code: 'DLR-RAD-03',
    name: 'Radiant AgroTech Distributions',
    business_name: 'Radiant Agro Dist',
    gstin: '29CCCC09876C1Z9',
    pan: 'CCCC09876C',
    cin: 'U01100KA2022PTC567432',
    address: '88, Agro Yard Extension, Hebbal',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560024',
    contact_email: 'ops@radiantagrotech.synthetic',
    contact_phone: '+91-9823000003',
    status: 'flagged',
    risk_tier: 'high',
    total_cases: 18,
    flagged_cases: 8,
    created_at: '2026-01-15T14:15:00Z',
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-001',
    customer_code: 'CUST-001',
    full_name: 'Rajesh Sharma (Synthetic)',
    contact_phone: '+91-9800000001',
    contact_email: 'rajesh.sharma@example.synthetic',
    address: 'Village Khed, Taluka Shirur',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '412218',
  },
  {
    id: 'CUST-002',
    customer_code: 'CUST-002',
    full_name: 'Meera Patel (Synthetic)',
    contact_phone: '+91-9800000002',
    contact_email: 'meera.patel@example.synthetic',
    address: 'Farm 4A, Bardoli Road',
    city: 'Surat',
    state: 'Gujarat',
    pincode: '394601',
  },
  {
    id: 'CUST-003',
    customer_code: 'CUST-003',
    full_name: 'GreenFields Agri Enterprises',
    contact_phone: '+91-9800000003',
    contact_email: 'billing@greenfields.synthetic',
    address: 'Sy 102/4, Devanahalli Rural',
    city: 'Bengaluru Rural',
    state: 'Karnataka',
    pincode: '562110',
  },
  {
    id: 'CUST-004',
    customer_code: 'CUST-004',
    full_name: 'Vikas Deshmukh (Synthetic)',
    contact_phone: '+91-9800000004',
    contact_email: 'vikas.deshmukh@example.synthetic',
    address: 'Survey 52, Baramati Farm Sector',
    city: 'Baramati',
    state: 'Maharashtra',
    pincode: '413102',
  },
  {
    id: 'CUST-005',
    customer_code: 'CUST-005',
    full_name: 'Anita Sundaram (Synthetic)',
    contact_phone: '+91-9800000005',
    contact_email: 'anita.sundaram@example.synthetic',
    address: 'Plot 18, Hosur Industrial Border',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560100',
  },
];

export const MOCK_CASES: Case[] = [
  {
    id: 'CAS-2026-001',
    case_number: 'CAS-2026-001',
    dealer_id: 'DLR-APX-01',
    dealer_name: 'Apex Solar Equipment Pvt Ltd',
    customer_id: 'CUST-001',
    customer_name: 'Rajesh Sharma',
    asset_type: 'Solar Water Pump 5HP',
    claimed_installation_address: 'Plot 12, Farm Sector B, Shirur, Pune, Maharashtra',
    claimed_lat: 18.8256,
    claimed_lng: 74.3789,
    loan_amount: 195000,
    status: 'verified',
    risk_level: 'low',
    notes: 'Scenario 1: Clean Case - Serial verified, invoice price matches benchmark.',
    created_at: '2026-01-12T10:00:00Z',
  },
  {
    id: 'CAS-2026-002',
    case_number: 'CAS-2026-002',
    dealer_id: 'DLR-APX-01',
    dealer_name: 'Apex Solar Equipment Pvt Ltd',
    customer_id: 'CUST-004',
    customer_name: 'Vikas Deshmukh',
    asset_type: 'Solar Inverter 5kVA',
    claimed_installation_address: 'Survey 52, Baramati Farm Sector, Baramati, Maharashtra',
    claimed_lat: 18.1523,
    claimed_lng: 74.5768,
    loan_amount: 55000,
    status: 'verified',
    risk_level: 'low',
    notes: 'Scenario 1: Clean Case - Telemetry and serial data fully aligned.',
    created_at: '2026-01-15T11:20:00Z',
  },
  {
    id: 'CAS-2026-003',
    case_number: 'CAS-2026-003',
    dealer_id: 'DLR-SUN-02',
    dealer_name: 'SunPower Retail & Infra Solutions',
    customer_id: 'CUST-002',
    customer_name: 'Meera Patel',
    asset_type: 'Solar Inverter 5kVA',
    claimed_installation_address: 'Farm 4A, Bardoli Road, Surat, Gujarat',
    claimed_lat: 21.1189,
    claimed_lng: 73.1145,
    loan_amount: 115000,
    status: 'under_review',
    risk_level: 'high',
    notes: 'Scenario 2: Inflated Price Case - Invoiced rate +121% over category benchmark.',
    created_at: '2026-01-20T14:30:00Z',
  },
  {
    id: 'CAS-2026-004',
    case_number: 'CAS-2026-004',
    dealer_id: 'DLR-SUN-02',
    dealer_name: 'SunPower Retail & Infra Solutions',
    customer_id: 'CUST-002',
    customer_name: 'Meera Patel',
    asset_type: 'Solar PV Panel System 5kW',
    claimed_installation_address: 'Farm 4B, Bardoli Road, Surat, Gujarat',
    claimed_lat: 21.1192,
    claimed_lng: 73.1150,
    loan_amount: 390000,
    status: 'flagged',
    risk_level: 'high',
    notes: 'Scenario 2: Inflated Price Case - Unit rates disproportionate to market.',
    created_at: '2026-01-24T09:15:00Z',
  },
  {
    id: 'CAS-2026-005',
    case_number: 'CAS-2026-005',
    dealer_id: 'DLR-RAD-03',
    dealer_name: 'Radiant AgroTech Distributions',
    customer_id: 'CUST-003',
    customer_name: 'GreenFields Agri Enterprises',
    asset_type: 'Solar Water Pump 5HP',
    claimed_installation_address: 'Sy 102/4, Devanahalli Rural, Bengaluru Rural, Karnataka',
    claimed_lat: 13.2489,
    claimed_lng: 77.7123,
    loan_amount: 190000,
    status: 'flagged',
    risk_level: 'critical',
    notes: 'Scenario 3: Duplicate Serial Case - Pump serial ASP-2025-99881 already registered to active loan in Pune.',
    created_at: '2026-02-01T15:45:00Z',
  },
  {
    id: 'CAS-2026-006',
    case_number: 'CAS-2026-006',
    dealer_id: 'DLR-RAD-03',
    dealer_name: 'Radiant AgroTech Distributions',
    customer_id: 'CUST-005',
    customer_name: 'Anita Sundaram',
    asset_type: 'Solar Inverter 10kW',
    claimed_installation_address: 'Plot 18, Hosur Industrial Border, Bengaluru, Karnataka',
    claimed_lat: 12.7845,
    claimed_lng: 77.7890,
    loan_amount: 105000,
    status: 'under_review',
    risk_level: 'critical',
    notes: 'Scenario 3: Duplicate Serial Case - Serial matches external lender registry.',
    created_at: '2026-02-05T12:00:00Z',
  },
  {
    id: 'CAS-2026-007',
    case_number: 'CAS-2026-007',
    dealer_id: 'DLR-RAD-03',
    dealer_name: 'Radiant AgroTech Distributions',
    customer_id: 'CUST-003',
    customer_name: 'GreenFields Agri Enterprises',
    asset_type: 'Micro-Irrigation Controller',
    claimed_installation_address: '88, Agro Yard Extension, Hebbal, Bengaluru, Karnataka',
    claimed_lat: 13.0358,
    claimed_lng: 77.5970,
    loan_amount: 34000,
    status: 'flagged',
    risk_level: 'high',
    notes: 'Scenario 4: Suspicious Relationship - Installation address identical to dealer business office.',
    created_at: '2026-02-15T16:20:00Z',
  },
  {
    id: 'CAS-2026-008',
    case_number: 'CAS-2026-008',
    dealer_id: 'DLR-RAD-03',
    dealer_name: 'Radiant AgroTech Distributions',
    customer_id: 'CUST-005',
    customer_name: 'Anita Sundaram',
    asset_type: 'Solar Inverter 5kVA',
    claimed_installation_address: '88, Agro Yard Extension, Hebbal, Bengaluru, Karnataka',
    claimed_lat: 13.0358,
    claimed_lng: 77.5970,
    loan_amount: 56000,
    status: 'flagged',
    risk_level: 'high',
    notes: 'Scenario 4: Suspicious Relationship - Customer phone cluster identical to dealer director record.',
    created_at: '2026-02-18T10:10:00Z',
  },
  {
    id: 'CAS-2026-009',
    case_number: 'CAS-2026-009',
    dealer_id: 'DLR-APX-01',
    dealer_name: 'Apex Solar Equipment Pvt Ltd',
    customer_id: 'CUST-001',
    customer_name: 'Rajesh Sharma',
    asset_type: 'Energy Storage 4.8kWh',
    claimed_installation_address: 'Plot 14, Farm Sector B, Shirur, Pune, Maharashtra',
    claimed_lat: 18.8260,
    claimed_lng: 74.3792,
    loan_amount: 115000,
    status: 'submitted',
    risk_level: 'requires_verification',
    notes: 'New submission - Pipeline execution pending.',
    created_at: '2026-02-28T09:00:00Z',
  },
  {
    id: 'CAS-2026-010',
    case_number: 'CAS-2026-010',
    dealer_id: 'DLR-SUN-02',
    dealer_name: 'SunPower Retail & Infra Solutions',
    customer_id: 'CUST-004',
    customer_name: 'Vikas Deshmukh',
    asset_type: 'Solar Water Pump 5HP',
    claimed_installation_address: 'Survey 56, Baramati Farm Sector, Baramati, Maharashtra',
    claimed_lat: 18.1530,
    claimed_lng: 74.5775,
    loan_amount: 188000,
    status: 'verification_pending',
    risk_level: 'medium',
    notes: 'Geo-tag telemetry variance (74km) flagged for physical field visit verification.',
    created_at: '2026-03-01T11:40:00Z',
  },
];

export const MOCK_RISK_SCORES: Record<string, RiskScore> = {
  'CAS-2026-001': {
    id: 'RSK-001',
    case_id: 'CAS-2026-001',
    overall_score: 8,
    risk_level: 'low',
    price_anomaly_score: 5,
    image_anomaly_score: 0,
    dealer_network_score: 8,
    serial_anomaly_score: 0,
    summary_reasoning: 'Clean case. Asset serial, invoice benchmark pricing, and image metadata fully consistent.',
    calculated_at: '2026-01-12T10:05:00Z',
  },
  'CAS-2026-003': {
    id: 'RSK-003',
    case_id: 'CAS-2026-003',
    overall_score: 74,
    risk_level: 'high',
    price_anomaly_score: 88,
    image_anomaly_score: 10,
    dealer_network_score: 35,
    serial_anomaly_score: 0,
    summary_reasoning: 'High risk identified due to +121% invoice price variance against market benchmark for 5kVA Inverter.',
    calculated_at: '2026-01-20T14:35:00Z',
  },
  'CAS-2026-005': {
    id: 'RSK-005',
    case_id: 'CAS-2026-005',
    overall_score: 96,
    risk_level: 'critical',
    price_anomaly_score: 15,
    image_anomaly_score: 85,
    dealer_network_score: 40,
    serial_anomaly_score: 99,
    summary_reasoning: 'Critical anomaly: Exact duplicate serial number match against active operational installation CAS-2026-001.',
    calculated_at: '2026-02-01T15:50:00Z',
  },
  'CAS-2026-007': {
    id: 'RSK-007',
    case_id: 'CAS-2026-007',
    overall_score: 82,
    risk_level: 'high',
    price_anomaly_score: 10,
    image_anomaly_score: 20,
    dealer_network_score: 95,
    serial_anomaly_score: 10,
    summary_reasoning: 'High risk: Entity relationship anomaly detected between dealer place of business and customer installation site.',
    calculated_at: '2026-02-15T16:25:00Z',
  },
};

export const MOCK_RISK_SIGNALS: Record<string, RiskSignal[]> = {
  'CAS-2026-003': [
    {
      id: 'SIG-001',
      case_id: 'CAS-2026-003',
      category: 'price',
      signal_name: 'BENCHMARK_PRICE_DEVIATION_HIGH',
      severity: 'high',
      confidence_score: 94.5,
      evidence_payload: {
        claimed_unit_price: 115000,
        benchmark_avg: 52000,
        variance_pct: 121.15,
        category: 'Solar Inverter',
      },
      description: 'Invoiced price (₹115,000) exceeds category benchmark upper band by +121.15%. Requires price justification review.',
      created_at: '2026-01-20T14:35:00Z',
    },
  ],
  'CAS-2026-005': [
    {
      id: 'SIG-002',
      case_id: 'CAS-2026-005',
      category: 'serial_asset',
      signal_name: 'DUPLICATE_SERIAL_CROSS_CASE_DETECTED',
      severity: 'critical',
      confidence_score: 99.8,
      evidence_payload: {
        serial_number: 'ASP-2025-99881',
        prior_case_id: 'CAS-2026-001',
        registered_date: '2025-08-14',
      },
      description: 'Serial number ASP-2025-99881 is already registered to active verified Case CAS-2026-001 in Pune.',
      created_at: '2026-02-01T15:50:00Z',
    },
    {
      id: 'SIG-003',
      case_id: 'CAS-2026-005',
      category: 'image',
      signal_name: 'PERCEPTUAL_HASH_NEAR_IDENTICAL',
      severity: 'high',
      confidence_score: 91.2,
      evidence_payload: {
        hamming_distance: 2,
        matched_image_id: 'IMG-001-NAMEPLATE',
      },
      description: 'Nameplate photo visual fingerprint matches uploaded image from prior case with hamming distance <= 2.',
      created_at: '2026-02-01T15:51:00Z',
    },
  ],
  'CAS-2026-007': [
    {
      id: 'SIG-004',
      case_id: 'CAS-2026-007',
      category: 'dealer_network',
      signal_name: 'SHARED_ADDRESS_DEALER_CUSTOMER',
      severity: 'high',
      confidence_score: 92.0,
      evidence_payload: {
        dealer_address: '88, Agro Yard Extension, Hebbal, Bengaluru',
        customer_address: '88, Agro Yard Extension, Hebbal, Bengaluru',
      },
      description: 'Borrower claimed installation location matches dealer registered place of business.',
      created_at: '2026-02-15T16:25:00Z',
    },
  ],
};

export const MOCK_EVIDENCE_ITEMS: Record<string, EvidenceItem[]> = {
  'CAS-2026-001': [
    {
      id: 'EVD-001',
      case_id: 'CAS-2026-001',
      type: 'invoice',
      title: 'Tax Invoice INV-APX-2026-081',
      status: 'verified',
      details: 'Total ₹195,000. HSN 84137010 matches 5HP solar submersible pump benchmark.',
      created_at: '2026-01-12T10:00:00Z',
    },
    {
      id: 'EVD-002',
      case_id: 'CAS-2026-001',
      type: 'image',
      title: 'Installation Site & Nameplate Photo',
      status: 'verified',
      details: 'EXIF coordinates (18.8256, 74.3789) match Shirur farm location within 20m tolerance.',
      created_at: '2026-01-12T10:02:00Z',
    },
    {
      id: 'EVD-003',
      case_id: 'CAS-2026-001',
      type: 'serial_check',
      title: 'Serial Registry Validation',
      status: 'verified',
      details: 'Serial ASP-2025-99881 verified unique in network registry at time of installation.',
      created_at: '2026-01-12T10:03:00Z',
    },
  ],
  'CAS-2026-003': [
    {
      id: 'EVD-004',
      case_id: 'CAS-2026-003',
      type: 'invoice',
      title: 'Tax Invoice INV-SUN-2026-114',
      status: 'suspicious',
      details: 'Unit price ₹115,000 vs benchmark range ₹45,000 - ₹58,000 (+121% inflation).',
      created_at: '2026-01-20T14:30:00Z',
    },
  ],
  'CAS-2026-005': [
    {
      id: 'EVD-005',
      case_id: 'CAS-2026-005',
      type: 'serial_check',
      title: 'Asset Serial Conflict',
      status: 'suspicious',
      details: 'Serial ASP-2025-99881 matches an existing installation registered 2025-08-14 in Pune.',
      created_at: '2026-02-01T15:45:00Z',
    },
    {
      id: 'EVD-006',
      case_id: 'CAS-2026-005',
      type: 'image',
      title: 'Perceptual Hash Duplicate',
      status: 'suspicious',
      details: 'Nameplate image visual hash matches previously submitted equipment photograph.',
      created_at: '2026-02-01T15:46:00Z',
    },
  ],
};

export const MOCK_VERIFICATION_TASKS: Record<string, VerificationTask[]> = {
  'CAS-2026-003': [
    {
      id: 'TSK-001',
      case_id: 'CAS-2026-003',
      task_type: 'document_reupload',
      status: 'pending',
      assigned_to: 'risk.officer1@diavn.synthetic',
      instructions: 'Request itemized OEM invoice and dealer price justification memo for SG-5KVA-HYBRID.',
      created_at: '2026-01-20T14:40:00Z',
    },
  ],
  'CAS-2026-005': [
    {
      id: 'TSK-002',
      case_id: 'CAS-2026-005',
      task_type: 'oem_serial_check',
      status: 'in_progress',
      assigned_to: 'lead.auditor@diavn.synthetic',
      instructions: 'Verify AquaSun OEM dispatch ledger for serial ASP-2025-99881.',
      findings: 'OEM dispatch record confirms single unit manufactured in Aug 2025, shipped to Pune distributor.',
      created_at: '2026-02-01T16:00:00Z',
    },
  ],
};
